name: publish

on: push
# on:
#   push:
#     tags:
#       - "v*"

jobs:
  publish:
    name: Publish to PyPI and hub.docker
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mcp-ollama
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build package
        run: uv run hatch build

      - name: Get version
        id: get_version
        run: |
          echo "version=$(uv run hatch version)" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mcp-ollama:${{ steps.get_version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mcp-ollama:latest

      - name: Publish package distributions to PyPI
        if: ${{ github.repository_owner == 'emgeee' }}
        uses: pypa/gh-action-pypi-publish@release/v1
